name: Order Repository CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  repository-integration-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: orderdb
          POSTGRES_USER: salman
          POSTGRES_PASSWORD: Salmon@123

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Verify PostgreSQL Connection
        run: |
          until pg_isready -h localhost -p 5432 -U postgres
          do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        env:
          PGPASSWORD: postgres

      - name: Execute Integration Tests
        working-directory: Gradle_Project
        env:
          JAVA_TOOL_OPTIONS: >
            -Ddb.url=jdbc:postgresql://localhost:5432/orderdb
            -Ddb.user=Salman
            -Ddb.password=Salmon@123
        run: ./gradlew clean test --info