name: Order Repository CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  repository-integration-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: orderdb
          POSTGRES_USER: salman
          POSTGRES_PASSWORD: Salmon@123

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U salman"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Executable
        run: chmod +x gradlew

      - name: Verify PostgreSQL Connection
        run: |
          until pg_isready -h localhost -p 5432 -U salman
          do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
        env:
          PGPASSWORD: Salmon@123

      - name: Execute Integration Tests
        env:
          JAVA_TOOL_OPTIONS: >
            -Ddb.url=jdbc:postgresql://localhost:5432/orderdb
            -Ddb.user=salman
            -Ddb.password=Salmon@123
        run: ./gradlew clean test --info


      - name: Checkout allure-b1 branch
        if: always()
        uses: actions/checkout@v4
        with:
              ref: allure-b1
              path: allure-b1

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
              allure_results: build/allure-results
              allure_report: build/allure-report
              gh_pages: allure-b1
              allure_history: allure-history

      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: allure-b1
            publish_dir: allure-history

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
              name: allure-results
              path: build/allure-results

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
              name: allure-report
              path: build/allure-report